language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake spec
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.2" 
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.3"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.4"
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.8"

notifications:
  slack:
    secure: FGIAZuQnrRB4L/Un36qd5+FyE+15vjehfbFWGSYHdw7ICU2M6Xh9sLoB60Fc8Rj4OqYSU0xvEi3FZjLoSZKBpldCPtxMQlnswNoaq4rg/G+JyTRvSNXta3IdTrX1RtVq/0+TQXVKZMbq4ztR0xT/H5jLLOGr95rCWYOB8jZi0o0=
